### ISSUE TITLE
Multiple subscribers subscribe same sticky event

### ISSUE THREAD

**Issue by thduc89** [greenrobot/EventBus#225]
For example I have 3 tab A-B-C in TabHost listen to event "DatabaseUpdatedEvent". When I do some database update in tab C, tab A & B will received sticky event "DatabaseUpdatedEvent", so they will update UI when I switch to them. The problem is when I switch to tab A, "onEvent" fired and I DON'T remove sticky event because I still have tab B listens to that event, and "onEvent" keep firing when I pause and resume app just by press Power button, and my logic code in "onEvent" method process again and again. For now I prevent this problem by making "public long timestamp" in my "DatabaseUpdatedEvent" model and assign System.currentTimeMillis() to it in constructor, so I can save the last event and check same event in "onEvent" method. The problem is solved but "onEvent" method will be called again and again is not a good optimization. Please let me know if someone has better solution for this problem or EventBus project will implement this feature in the next release version.

**Comment by AgentKnopf** [comment]
Maybe sticky events aren't the best choice for your use case? Because based on what you said, this is how sticky events are currently working: Whenever you subscribe, you're immediately provided with the last posted sticky. Which happens in onResume of a Fragment for instance (each time).

Assuming that each tab is a fragment, would it be an option if the parent activity subscribed to those events (that are produced by the fragments), rather than having each fragment subscribe to them and have the Activity then forward events to the currently visible fragment? Alternatively you could limit the Activity to only passing on previous events if the Fragment has been swapped for another one (like B replaced A) by switching tabs.

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
