### ISSUE TITLE
Update Jcenter Dependency to 3.0.0

### ISSUE THREAD

**Issue by jaredsburrows** [greenrobot/EventBus#256]
@greenrobot

Jcenter dependency is still on the beta: https://bintray.com/greenrobot/maven/de.greenrobot%3Aeventbus/view

**Comment by talklittle** [comment]
:+1:

**Comment by talklittle** [comment]
Oops the JCenter dependency is actually available already: http://jcenter.bintray.com/org/greenrobot/eventbus/3.0.0/

Notice the group name changed to `org.greenrobot` instead of `de.greenrobot`

But yeah, the Bintray page hasn't been updated. I guess it is due to JCenter mirroring Maven Central, rather than the library being deployed directly through Bintray.

**Comment by jaredsburrows** [comment]
@talklittle It was not when I created this issue.

**Comment by jaredsburrows** [comment]
It is now `compile 'org.greenrobot:eventbus:3.0.0'` and not `compile 'de.greenrobot:eventbus:3.0.0'`.
