### ISSUE TITLE
Fragment not registered

### ISSUE THREAD

**Issue by j-garin** [greenrobot/EventBus#259]
Hello.

I am developing an app for android TV and got this issue. One of the fragments i use (extends android.support.v17.leanback.app.BrowseFragment) doesn't get registered with EventBus.
Here's my service's code:

`EventBus.getDefault().post(new EventSyncComplete(EventSyncComplete.RESULT_CODE_OK));`

and my fragment's code:

```
public class FragmentMain extends BrowseFragment {
    @Override
    public void onResume() {
        Log.d(TAG, "onResume");
        super.onResume();
        EventBus.getDefault().register(this);
    }

    @Override
    public void onPause() {
        EventBus.getDefault().unregister(this);
        super.onPause();
    }

    @Subscribe
    public void onEventMainThread(EventSyncComplete event) {
            Log.d(TAG, "onEventMainThread");
         }
    }
}

```

And even i can see that the fragment is created and onResume() is called, i keep getting these messages:
```
02-23 11:14:36.068 14157-14215/com.xxxxxx D/EventBus: No subscribers registered for event class com.xxxxxx.core.Events.EventSyncComplete
02-23 11:14:36.069 14157-14215/com.xxxxxx D/EventBus: No subscribers registered for event class de.greenrobot.event.NoSubscriberEvent
```
Am i missing something?

**Comment by nasuellia** [comment]
I'm having the same exact problem.

I opened a [discussion on the /androiddev subreddit](https://www.reddit.com/r/androiddev/comments/47797p/i_need_a_help_with_greenrobots_eventbus/) and no one has been able to help me up to this point.

**Comment by jasco** [comment]
You might use `EventBus.getDefault().hasSubscriberForEvent(EventSyncComplete.class)` to verify that the receiver has been registered from the receiver's point of view after registration and from the sender's point of view on post.

According to the thread @nasuellia cited the problem ended up being that `register` and `post` where being called on different instances of EventBus.  In that case you might expect to see different results from the two tests.

In my case, I encountered a similar symptom that turned out to be the subscribed method was package scope rather than public.  So in my case it was not subscribed in either case.

Also, if you are using proguard, verify that you have added the proguard configuration for EventBus v3.

**Comment by mores** [comment]
I was having a similar issue, in order to get mine to work I had to wrap them in a Handler.....

`new android.os.Handler().post(new Runnable() {
    public void run(){
      org.greenrobot.eventbus.EventBus.getDefault().post( new EventSyncComplete(EventSyncComplete.RESULT_CODE_OK) );
   }
});`

**Comment by j-garin** [comment]
moving from de.greenrobot.*** to org.greenrobot.*** solved the issue
