### ISSUE TITLE
EventBus posts to a subscriber which is removed during post process.

### ISSUE THREAD

**Issue by neokim** [greenrobot/EventBus#318]
[Stackoverflow question](http://stackoverflow.com/questions/37408467/eventbus-posts-to-unregistered-subscriber)

While using EventBus, I have faced an unexpected situation that a subscription method of a Fragment is called one time even after the Fragment is unregistered.

Scenario is like this. I have an Activity containing a layout which any Fragment can be put. The Activity starts with a certain Fragment.

The Activity and the Fragment register themselves on their onResume() and unregister on onPause(). They have their own handlers for each for an event of same type.

By a dispatched event, the Activity replaces the Fragment with another by some condition. Then, the Fragment's onPause() gets called during removal process and EventBus.getDefault().unregister(this) is also executed.

Here, then, I expect the Fragment's handler not to be called from now. BUT it is called one time right after the Fragment is unregistered.

It seems like that EventBus doesn't handle the case of any subscriber is unregistered while event posting process.

**Comment by greenrobot-team** [comment]
As the event was submitted on the main thread before the unregister call, and is to be received on the same (main) thread, the event will be posted to all subscribers that exist at the moment, yes.

If you do not want the event to be handled if your fragment is paused, you might check for `!isResumed()` before handling the event.

Or post the event on a thread different from the main thread and change to `@Subscribe(threadMode = ThreadMode.MAIN)`. Because if the posting and receiving thread are different, the subscription will be checked again before invoking the subscriber method.

The relevant code is at [`EventBus.postSingleEventForEventType()`](https://github.com/greenrobot/EventBus/blob/V3.0.0/EventBus/src/org/greenrobot/eventbus/EventBus.java#L387-L391). @greenrobot Can this be allowed?

**Comment by greenrobot-team** [comment]
Tracking this further with #307 which has a potential fix.
