### ISSUE TITLE
Clarify access modifier requirements for @Subscribe methods

### ISSUE THREAD

**Issue by stefan-girlich** [greenrobot/EventBus#348]
I noticed that methods annotated with _@Subscribe_ may be declared _protected_ and will still be successfully invoked as event callbacks - for debug builds.
When creating release builds, this does not seem to be the case anymore: Event callback method are required to be _public_, otherwise they will not be invoked.

- Can you confirm this behavior?
- The [Getting started](http://greenrobot.org/eventbus/documentation/how-to-get-started/) page contains only code examples using _public_, but does not specify it as a requirement.
- I didn't test if at least the usual _No subscribers registered for event class_ log warning is printed during runtime. But I think that any existing annotated non-_public_ methods for an event type might be ignored as long as there is _one_ single _public_ callback method.

**Setup**
- EventBus 3.0.0
- Test device: Android 5.1.1
- build types:
```
        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.debugConfig
        }
        
        qa {
            debuggable true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.releaseConfig
        }
```

**Comment by greenrobot-team** [comment]
Is it not kind of implied that in Java for an external class not in your package (here EventBus) to access a method in your class, that it needs to be public?

As for the subscriber methods not getting called, I guess this is because your ProGuard config will remove non-public subscriber methods (if you added the [rules from the docs](http://greenrobot.org/eventbus/documentation/proguard/)). -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
