### ISSUE TITLE
Remove these checks will improve performance, isn't it?

### ISSUE THREAD

**Issue by yuxiaofei93** [greenrobot/EventBus#404]
When I Read the source code.  I can not understand the follow piece of code in class `HandlerPoster` and `BackgroundPoster`. As far as I understand, only one thread can run through these code. Because both main thread and background thread are only one per process. So it is not necessary to use synchronize and check null twice. 

And remove these check will improve performance, isn't it?
``` java
            while (true) {
                PendingPost pendingPost = queue.poll();
                if (pendingPost == null) {
                    synchronized (this) {
                        // Check again, this time in synchronized
                        pendingPost = queue.poll();
                        if (pendingPost == null) {
                            handlerActive = false;
                            return;
                        }
                    }
                }
                eventBus.invokeSubscriber(pendingPost);
                //...
            }
```

**Comment by markuspfeiffer** [comment]
`synchronized` **is** required, because writes to and reads from the queue happen on separate threads.

Example for BackgroundPoster:
Take a look at `queue.enqueue`, which is called by the enqueue method. This method is executed on the calling thread (and is also inside a synchronized block).

Afterwards the BackgroundPoster instance is passed into an executor. This means its run method is executed on another thread. The run method then calls `queue.poll` periodically.

This means `queue.enqueue` and `queue.poll` are called on separate threads, which requires synchronization.

The double null check is known as double-checked locking. This is a performance optimization, because it means a lock is only obtained when the first poll returns a null value.

**Comment by yuxiaofei93** [comment]
Thank you for your explanation. I got it now.

**Comment by greenrobot-team** [comment]
Thanks @markuspfeiffer. You can also read up about [double-checked locking on Wikipedia](https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java).

Closing this then as the implementation here seems valid (not constructing a new instance). -ut

**Comment by boundray** [comment]
> queue

Maybe synchronized is required,but i do not agree with your answer.
See PendingPostQueue,the method enqueue and poll are all synchronized.
