### ISSUE TITLE
Permission Request interfere with Events

### ISSUE THREAD

**Issue by moritzm** [greenrobot/EventBus#432]
Hello,
i use EventBus on many places, but now i was running in a strange issue.

When i have a permission request window open (the one from the Android system itself), it will interfere my events coming from places startet before this requests pops up. So the events are not being caught. I guess for now the workaround will be with a sticky event.

Best regards,
Moritz

**Comment by william-ferguson-au** [comment]
The dialog won't have interfered with your events. What is almost certainly happening is that the component that you registered as a listener has unregistered itself because showing the dialog has forced it to be paused or stopped (or perhaps destroyed). 

You need to get a better understanding of the Fragment and Activity life cycles. And then decide in which lifecycle methods you want o register/unregister your listeners.

**Comment by moritzm** [comment]
Hey @william-ferguson-au 
thanks for the answer. Well, this might be the problem. I will check it tomorrow and let you know :-)

**Comment by moritzm** [comment]
The hint with the life cycle is great. It works now. Thx @william-ferguson-au
