### ISSUE TITLE
Kotlin integration needed

### ISSUE THREAD

**Issue by nandorrb** [greenrobot/EventBus#441]
Hi, 
 I'm starting to migrate from java to kotlin, where I found a NPE generator,  here:

```kotlin
@Subscribe
    fun AsynchronousResponse(ResponseObject_AsynchronousResponse: ResponseObject) {
        Helper.processAsynchronousRequest(ResponseObject_AsynchronousResponse)
    }
```
Problem Fixed by doing this:

```kotlin
@Subscribe
    fun AsynchronousResponse(ResponseObject_AsynchronousResponse: ResponseObject) {
        val ResponseObject_AsynchronousResponse2: ResponseObject = GsonSingleton.getInstance().objectFromJson(GsonSingleton.getInstance().objectToJson(ResponseObject_AsynchronousResponse), ResponseObject::class.java) as ResponseObject
        Helper.processAsynchronousRequest(ResponseObject_AsynchronousResponse2)
    }
```
Just wanted to document that, and also to check whether we can start migrating to kotlin.

Thank you for your time

**Comment by greenrobot-team** [comment]
This is likely an issue with your own code. Do you have a stacktrace?

I tested EventBus using an all-Kotlin project and it works fine. However, to use the annotation processor you need to [use `kapt` instead of `annotationProcessor`](https://kotlinlang.org/docs/tutorials/android-frameworks.html). Due to a bug this requires [updating to the preview Android Gradle Plugin and Gradle 4 RC1](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html).

-ut

**Comment by nandorrb** [comment]
thank you for answering @greenrobot-team , I just tried what you said.
I think the problem was on how Gson work, it doesn't serialize variables not sent by the server. which was creating a NPE.
Thanks.
Problem Solved.
