### ISSUE TITLE
Build with proguard fails when update from 3.0.0 to 3.1.1

### ISSUE THREAD

**Issue by thelittlefireman** [greenrobot/EventBus#510]
hi,
Build with proguard fails when update from 3.0.0 to 3.1.1 with lots of : 
`com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type java.lang.reflect.Type using a local variable of type java.lang.Class[].`
or other

They are related to the fact that i used classpath 'com.android.tools.build:gradle:3.0.0' because i think you revert back to classpath 'com.android.tools.build:gradle:2.3.3'

Could you please reupdate to 3.0.0 it's the norm now.

Thanks

Thomas

**Comment by greenrobot-team** [comment]
We are just using the Android Gradle Plugin for our test projects. EventBus itself does not use or require the Android Gradle plugin.

It is [suggested on Stack Overflow](https://stackoverflow.com/questions/45025120/uncaught-translation-error-com-android-dx-cf-code-simexception-local-0007-inv) that your exception is caused by Instant Run, try to disable it.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
