### ISSUE TITLE
suggestion: add an option to throw Exceptions as they are

### ISSUE THREAD

**Issue by yizhixiaotaozi** [greenrobot/EventBus#624]
In many backend applications, we use exceptions to deal with business logic。For an example: 
if(accountAmount < 100) throw new AccountException("000001","lack of money");
There will be a interceptor to translate this exception to message, then front pages can show this message to users.  
throwSubscriberException(true)  wrap the original exception like 
if (throwSubscriberException) {
    throw new EventBusException("Invoking subscriber failed", cause);
}
So we have to modify interceptor to use EventBus.
may be , if cause instanceof rumtime  just throw it

**Comment by yizhixiaotaozi** [comment]
backend applications always use ThreadMode.POST , cause they manipulate database, and have to ensure transaction。 Throwing Exception both rollbacks database and sends message back to the caller.

**Comment by SaeedJinat** [comment]
i think instead of asking for an option to unwrap the exception , 
do what Eventbus is already doing : use exception events . 

looking at the snippet that post your event to its subscriber :

```
void invokeSubscriber(Subscription subscription, Object event) {
        try {
            subscription.subscriberMethod.method.invoke(subscription.subscriber, event);
        } catch (InvocationTargetException e) {
            handleSubscriberException(subscription, event, e.getCause());
        } catch (IllegalAccessException e) {
            throw new IllegalStateException("Unexpected exception", e);
        }
    }
```

as you can see , reflected method invocation exceptions are caught and re-delivered as events . 

looking also at the inside of **handleSubscriberException()**  : 
```
if (event instanceof SubscriberExceptionEvent) {
            if (logSubscriberExceptions) {
                // Don't send another SubscriberExceptionEvent to avoid infinite event recursion, just log
                logger.log(Level.SEVERE, "SubscriberExceptionEvent subscriber " + subscription.subscriber.getClass()
                        + " threw an exception", cause);
                SubscriberExceptionEvent exEvent = (SubscriberExceptionEvent) event;
                logger.log(Level.SEVERE, "Initial event " + exEvent.causingEvent + " caused exception in "
                        + exEvent.causingSubscriber, exEvent.throwable);
            }
        } else {
            if (throwSubscriberException) {
                throw new EventBusException("Invoking subscriber failed", cause);
            }
            if (logSubscriberExceptions) {
                logger.log(Level.SEVERE, "Could not dispatch event: " + event.getClass() + " to subscribing class "
                        + subscription.subscriber.getClass(), cause);
            }
            if (sendSubscriberExceptionEvent) {
                SubscriberExceptionEvent exEvent = new SubscriberExceptionEvent(this, cause, event,
                        subscription.subscriber);
                post(exEvent);
            }
        }
```

as you can see eventbus throw them as their own **EventBusException** . 
there is also the option you could configure t use which enables you to recieves eventbus wrapper for those exceptions  using ** SubscriberExceptionEvent** class .

### 
another possible manual solution you could do is to take advantage that events can be subscribed either as a class event or as an interface it implements . 
so you can make your exceptions implement (for say ) a **IEventException**  interface and register to those interface events as if you are receiving the exception itself . 

hope i was helpful .

**Comment by greenrobot-team** [comment]
@SaeedJinat Thanks!
Also mentioned in the docs.
https://greenrobot.org/eventbus/documentation/configuration/
