### ISSUE TITLE
Handling events on rotation

### ISSUE THREAD

**Issue by naderz** [greenrobot/EventBus#87]
Green robot works fine for me. But I have this rare case when lets say I fire a service call from an activity, and the moment the service call is returned to greenrobot to post it back to activity .. the user rotates. So the current state of activity will be destoryed and getting recreated but not created yet.. in that case my reult will not be handled.
Any ideas how to handle this using green robot .. I know its really hard to happen but it might.
What I was thinking in send a stickypost instead of a regular but I dono how appropriate that would be.

**Comment by consp1racy** [comment]
I have not tried this yet but posting sticky events and using EventBus#removeStickyEvent after consuming these could work. You'll have to preserve processed data via standard methods like onSaveInstance.

**Comment by marcochin** [comment]
If anyone searches for this issue maybe my solution can help. I have a singleton that stores a queue. Since singleton will not be destroyed, so I can always have access to it. The queue maintains the order of the events so we never process out of order.

• If an event is sent with no subscriber OR if the queue is not empty, the event will be put into the queue. This can occur during orientation change which can cause a subscriber to unregister right as the event is posted. 
• After orientation change and app resumes, it should process events from this queue until it is empty!

Let me know if this is helpful!

**Comment by jdestremps** [comment]
So a related question I have is.... Does this EventBus not handle queing (as in a JMS queue)?  I thought that was one of the reasons for having an event bus... to, for example, make a network call, but the activity that was going to consume it has now been backgrounded (because you got a phone call or whatever.) and so you want to subscribe to the bus again and if it has anything in the queue, it will give it to you.  Does this event but not handle queing like this?

**Comment by consp1racy** [comment]
> Does this EventBus not handle queing

Last of each sticky event remains cached. Unless you manually remove it. 

Removing a sticky event typically isn't safe because multiple subjects may be listening and you'd be making one of them responsible for cutting access to the event. One of the subscribers never knows about the state of all subscribers.

So you don't remove the sticky event. And process the same event on each configuration change (if you registerSticky in onStart).

That doesn't sound fancy for performance. It also sounds like a lousy replacement for a proper persistent storage such as SQLite database, or Realm or something that backs up data to disk (and in better case holds some kind of in memory cache).

Implement proper persistent model. Don't use sticky broadcasts.

**Comment by jdestremps** [comment]
Yeah, I agree.  Doesn't seem that helpful for subscribers that may be down.  Will have to implement my own queue in a service or something.  Lame...
